// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aegis.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AegisDbContext))]
    partial class AegisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Aegis.Domain.Entities.Annotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId");

                    b.ToTable("Annotations", (string)null);
                });

            modelBuilder.Entity("Aegis.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalKey")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "Aegis.Domain.Entities.Asset.Location#Coordinate", b1 =>
                        {
                            b1.Property<double>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("Longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey");

                    b.HasIndex("InvestigationId");

                    b.HasIndex("InvestigationId", "Type", "ExternalKey")
                        .IsUnique()
                        .HasFilter("[ExternalKey] IS NOT NULL");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("Aegis.Domain.Entities.FlightTrackPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("BaroAltitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Callsign")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("GeoAltitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Heading")
                        .HasColumnType("REAL");

                    b.Property<string>("Icao24")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<bool>("OnGround")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Velocity")
                        .HasColumnType("REAL");

                    b.Property<double?>("VerticalRate")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.HasIndex("Icao24", "Time");

                    b.ToTable("FlightTrackPoints", (string)null);
                });

            modelBuilder.Entity("Aegis.Domain.Entities.Geofence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeometryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId");

                    b.ToTable("Geofences", (string)null);
                });

            modelBuilder.Entity("Aegis.Domain.Entities.Investigation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Investigations", (string)null);
                });

            modelBuilder.Entity("Aegis.Domain.Entities.TimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvestigationId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OccurredAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvestigationId", "OccurredAt");

                    b.ToTable("TimelineEvents", (string)null);
                });

            modelBuilder.Entity("Aegis.Infrastructure.Data.Entities.GeocodeCacheEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpiresAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("QueryHash")
                        .IsUnique();

                    b.ToTable("GeocodeCache", (string)null);
                });

            modelBuilder.Entity("Aegis.Infrastructure.Data.Entities.NewsItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedId");

                    b.HasIndex("LinkHash")
                        .IsUnique();

                    b.HasIndex("PublishedAt");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("NewsItems", (string)null);
                });

            modelBuilder.Entity("Aegis.Infrastructure.Data.Entities.IntegrationSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("IntegrationSettings", (string)null);
                });

            modelBuilder.Entity("Aegis.Infrastructure.Data.Entities.RssFeedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultRegionQuery")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("RssFeeds", (string)null);
                });

            modelBuilder.Entity("Aegis.Domain.Entities.Annotation", b =>
                {
                    b.HasOne("Aegis.Domain.Entities.Investigation", null)
                        .WithMany("Annotations")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aegis.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Aegis.Domain.Entities.Investigation", null)
                        .WithMany("Assets")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aegis.Domain.Entities.Geofence", b =>
                {
                    b.HasOne("Aegis.Domain.Entities.Investigation", null)
                        .WithMany("Geofences")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aegis.Domain.Entities.TimelineEvent", b =>
                {
                    b.HasOne("Aegis.Domain.Entities.Investigation", null)
                        .WithMany("Timeline")
                        .HasForeignKey("InvestigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aegis.Infrastructure.Data.Entities.NewsItemEntity", b =>
                {
                    b.HasOne("Aegis.Infrastructure.Data.Entities.RssFeedEntity", "Feed")
                        .WithMany("NewsItems")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("Aegis.Domain.Entities.Investigation", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("Assets");

                    b.Navigation("Geofences");

                    b.Navigation("Timeline");
                });

            modelBuilder.Entity("Aegis.Infrastructure.Data.Entities.RssFeedEntity", b =>
                {
                    b.Navigation("NewsItems");
                });

            modelBuilder.Entity("Aegis.Infrastructure.Data.Entities.CensysApiUsageEntity", b =>
                {
                    b.Property<string>("MonthKey")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<int>("QueryCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("MonthKey");

                    b.ToTable("CensysApiUsage", (string)null);
                });

            modelBuilder.Entity("Aegis.Infrastructure.Data.Entities.CountryIngestStateEntity", b =>
                {
                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<int>("CidrCursor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchPageToken")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SearchComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverpassTileIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverpassWarmComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShodanRegionIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShodanWarmComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrefetchWarmComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastPrefetchUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CountryCode");

                    b.ToTable("CountryIngestStates", (string)null);
                });

            modelBuilder.Entity("Aegis.Infrastructure.Data.Entities.DiscoveredHostEntity", b =>
                {
                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CensysFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsUp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastProbeAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<double?>("Lng")
                        .HasColumnType("REAL");

                    b.Property<string>("Org")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Product")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Transport")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("VulnerabilitiesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ip");

                    b.HasIndex("CensysFetchedAt");

                    b.HasIndex("CountryCode", "Lat", "Lng");

                    b.ToTable("DiscoveredHosts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
